OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-9p2vA8PvWogRQ9p500783cD35b9a4815A4Af10661d69B4F6"

#GLMModel:
#  model_url: "https://api.bltcy.ai/v1"
#  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"